version: "3.9"

services:
  app:
    image: krystiansiupik/palletes:latest
    container_name: mymarket-app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    restart: unless-stopped
