version: "3.9"

services:
  app:
    build:
      context: . #katalog, który Docker wysyła do silnika builda jako źródło plików.
      target: prod
    container_name: mymarket-app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    restart: unless-stopped
