version: "3.9"

services:
  app:
    build:
      target: dev #wybiera z dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    command: npm run dev
